<?php

namespace RefugeBundle\Repository;

/**
 * campRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class campRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * campRepository constructor.
     */
    /*  public function __construct(ManagerRegistry $registry)
      {
          parent::__construct($registry, camp::class);

      }*/

    public function updateCapacityMinus($camp){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
        update RefugeBundle:camp c set c.capacity = (c.capacity-1) 
        where c.id = :camp'

        )->setParameter('camp', $camp)->getResult();
        return $query;


    }
    public function updateCapacityPlus($camp){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
        update RefugeBundle:camp c set c.capacity = (c.capacity+1) 
        where c.id = :camp'

        )->setParameter('camp', $camp)->getResult();
        return $query;


    }
}

