<?php

namespace RefugeBundle\Repository;

/**
 * RefugeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefugeRepository extends \Doctrine\ORM\EntityRepository
{
}
